### PR TITLE
Flatten

### PR DESCRIPTION
**Pull request by josef-hak**
https://projects.engineering.redhat.com/browse/RHCLOUD-2848

### CODE REVIEW

**Review by jharting — CHANGES_REQUESTED** [review]
Looks great. One thing - a tag value is optional (may be null). Can you add a test for that scenario just in case?

**Comment by josef-hak** [comment]
@jharting, I think it's already included [here](https://github.com/RedHatInsights/flattenlistsmt/blob/743b1016485d68ba5716d0d263e37e590e7dd45e/src/test/java/com/redhat/insights/flattenlistsmt/FlattenListTest.java#L203).

**Comment by jharting** [comment]
@Josca no, that one tests when `tags` is null. What I mean is that a tag, which consists of a namespace, key and value may have the value null `{Sat: {prod: [null]}}`

**Comment by josef-hak** [comment]
@jharting ok, added.

**Review by jharting — APPROVED** [review]

**Pull request merged**
